-- Seed for the realtime live integration suite (realtime_live_spec.rb, US-051).
--
-- The postgres_changes example needs a `public.todos` table with realtime
-- enabled. Apply this against the local Supabase stack the suite points at:
--
--   psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" \
--     -f spec/integration/realtime_seed.sql
--
-- Or drop it into your scratch project's supabase/migrations/ so a fresh
-- `supabase start` / `supabase db reset` provisions it automatically.
--
-- NOTE: the Realtime server reads the publication when it boots. If you add
-- the table to the publication while the stack is already running, restart
-- the realtime container (`docker restart supabase_realtime_<project>`) or
-- postgres_changes frames will not be delivered.
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  description text,
  is_completed boolean default false
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'todos'
  ) then
    alter publication supabase_realtime add table public.todos;
  end if;
end $$;
